Add `cppLibrary` and `cppApplication` software types
gradle/declarative-gradle pull request #77
Opened 2024-05-24 06:19 UTC by adammurdoch

2024-05-24 06:23 UTC, oleg-nenashev approved these changes

2024-05-26 13:14 UTC, ghale requested changes
I don't think anything _must_ be changed, but the plugin name in the buid.gradle _should_ be fixed, I think.  The other comments are just suggestions...

2024-05-26 13:14 UTC, ghale commented on unified-prototype/unified-plugin/plugin-cpp/build.gradle.kts
> +        create("swift-ecosystem") {
❓ Looks like a cut/paste oversight...
```suggestion
        create("cpp-ecosystem") {
```

2024-07-01 14:24 UTC, ghale approved these changes

2024-07-01 15:26 UTC, merged

2024-07-01 16:10 UTC, oleg-nenashev commented
Merci @ghale !